---
- name: "Restart {{ graylog_service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ graylog_service_name }}"
    state: stopped
  notify: Reload systemd for graylog

- name: Reload systemd for graylog
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  notify: "Start {{ graylog_service_name }}"

- name: "Start {{ graylog_service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ graylog_service_name }}"
    enabled: true
    state: started
